#!/usr/bin/env python3
"""Bootstrap a deterministic local Rust toolchain for this container.

Rules enforced by this script:
- extract Rust archive components with Python tarfile only;
- extract only rustc, cargo, and rust-std-x86_64-unknown-linux-gnu;
- merge component bin/lib contents into one prefix;
- write Cargo config for the internal sparse registry so dependencies can be fetched;
- write /mnt/data/rustc-session.env for later shell commands;
- validate rustc, cargo, sysroot, target-libdir, offline cargo run, and dependency fetch.

Default mode is idempotent: reuse the existing prefix when rustc+cargo exist.
Use --force to delete and rebuild the prefix, cargo home, temp dir, and probe project.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tarfile
import textwrap
from pathlib import Path


DEFAULT_ARCHIVE = Path("/mnt/data/rust-1.75.0-x86_64-unknown-linux-gnu.tar.gz")
DEFAULT_TMP = Path("/mnt/data/rustc_python_install_test")
DEFAULT_PREFIX = Path("/mnt/data/rustc-python-install-prefix")
DEFAULT_CARGO_HOME = Path("/mnt/data/rustc-python-cargo-home")
DEFAULT_PROBE = Path("/mnt/data/rust-python-test-project")
DEFAULT_LIBRARY_PROBE = Path("/mnt/data/rust-library-download-probe")
DEFAULT_ENV_FILE = Path("/mnt/data/rustc-session.env")
DEFAULT_LAUNCHER_DIR = Path("/usr/local/bin")
DEFAULT_REGISTRY_URL = (
    "sparse+https://packages.applied-caas-gateway1.internal.api.openai.org/"
    "artifactory/api/cargo/cargo-public/index/"
)
LAUNCHER_MARKER = "# generated-by: bootstrap_rustc_session.py"

WANTED_COMPONENTS = {
    "rustc",
    "cargo",
    "rust-std-x86_64-unknown-linux-gnu",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, default=Path(os.environ.get("RUST_ARCHIVE", DEFAULT_ARCHIVE)))
    parser.add_argument("--tmp", type=Path, default=Path(os.environ.get("RUST_TMP", DEFAULT_TMP)))
    parser.add_argument("--prefix", type=Path, default=Path(os.environ.get("RUST_PREFIX", DEFAULT_PREFIX)))
    parser.add_argument(
        "--cargo-home",
        type=Path,
        default=Path(os.environ.get("RUST_CARGO_HOME", os.environ.get("CARGO_HOME", DEFAULT_CARGO_HOME))),
    )
    parser.add_argument("--probe", type=Path, default=Path(os.environ.get("RUST_PROBE", DEFAULT_PROBE)))
    parser.add_argument(
        "--library-probe",
        type=Path,
        default=Path(os.environ.get("RUST_LIBRARY_PROBE", DEFAULT_LIBRARY_PROBE)),
    )
    parser.add_argument("--env-file", type=Path, default=Path(os.environ.get("RUST_ENV_FILE", DEFAULT_ENV_FILE)))
    parser.add_argument(
        "--registry-url",
        default=os.environ.get("CARGO_REGISTRY_URL", DEFAULT_REGISTRY_URL),
        help="sparse registry URL used to fetch crates.io dependencies through Cargo",
    )
    parser.add_argument("--library-crate", default=os.environ.get("RUST_LIBRARY_CRATE", "itoa"))
    parser.add_argument("--library-version", default=os.environ.get("RUST_LIBRARY_VERSION", "1.0.18"))
    parser.add_argument(
        "--launcher-dir",
        type=Path,
        default=Path(os.environ.get("RUST_LAUNCHER_DIR", DEFAULT_LAUNCHER_DIR)),
        help="directory on PATH where cargo/rustc launcher scripts should be installed",
    )
    parser.add_argument("--force", action="store_true", help="delete and rebuild all generated Rust bootstrap paths")
    parser.add_argument(
        "--force-launchers",
        action="store_true",
        help="overwrite existing cargo/rustc launchers even if they were not generated by this script",
    )
    parser.add_argument(
        "--no-install-launchers",
        action="store_true",
        help="do not install cargo/rustc launcher scripts into the launcher directory",
    )
    parser.add_argument("--skip-probe", action="store_true", help="skip cargo run --offline probe")
    parser.add_argument("--skip-library-probe", action="store_true", help="skip dependency fetch/build probe")
    parser.add_argument("--skip-registry-config", action="store_true", help="do not write Cargo registry config")
    return parser.parse_args()


def is_safe_member(member_name: str, destination: Path) -> bool:
    destination = destination.resolve()
    target = (destination / member_name).resolve()
    return target == destination or str(target).startswith(str(destination) + os.sep)


def have_toolchain(prefix: Path) -> bool:
    rustc = prefix / "bin" / "rustc"
    cargo = prefix / "bin" / "cargo"
    return rustc.exists() and os.access(rustc, os.X_OK) and cargo.exists() and os.access(cargo, os.X_OK)


def reset_generated_paths(paths: list[Path]) -> None:
    for path in paths:
        if path.exists():
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()


def copy_tree_contents(src: Path, dst: Path) -> None:
    if not src.exists():
        raise RuntimeError(f"missing component path: {src}")
    dst.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        target = dst / item.name
        if item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True)
        else:
            shutil.copy2(item, target)


def merged_target_for_member(member_name: str, prefix: Path) -> Path | None:
    parts = member_name.split("/")
    if len(parts) < 4:
        return None

    component = parts[1]
    section = parts[2]
    tail = parts[3:]

    if component == "cargo" and section == "bin":
        return prefix / "bin" / Path(*tail)
    if component == "rustc" and section == "bin":
        return prefix / "bin" / Path(*tail)
    if component == "rustc" and section == "lib":
        return prefix / "lib" / Path(*tail)
    if component == "rust-std-x86_64-unknown-linux-gnu" and section == "lib":
        return prefix / "lib" / Path(*tail)
    return None


def extract_regular_or_dir_to_target(tf: tarfile.TarFile, member: tarfile.TarInfo, target: Path, prefix: Path) -> None:
    resolved_prefix = prefix.resolve()
    resolved_target = target.resolve()
    if resolved_target != resolved_prefix and not str(resolved_target).startswith(str(resolved_prefix) + os.sep):
        raise RuntimeError(f"unsafe resolved target outside prefix: {target}")

    if member.isdir():
        target.mkdir(parents=True, exist_ok=True)
        return

    if not member.isfile():
        raise RuntimeError(f"unsupported tar member type for direct merge: {member.name}")

    source = tf.extractfile(member)
    if source is None:
        raise RuntimeError(f"could not read tar member: {member.name}")

    target.parent.mkdir(parents=True, exist_ok=True)
    with source, target.open("wb") as out:
        shutil.copyfileobj(source, out)
    target.chmod(member.mode & 0o777)


def extract_components_with_python_tarfile(archive: Path, tmp: Path, prefix: Path) -> None:
    if not archive.exists():
        raise FileNotFoundError(f"missing archive: {archive}")

    reset_generated_paths([tmp])
    (prefix / "bin").mkdir(parents=True, exist_ok=True)
    (prefix / "lib").mkdir(parents=True, exist_ok=True)

    root_name: str | None = None
    seen_components: set[str] = set()
    extracted_targets = 0

    with tarfile.open(archive, "r:gz") as tf:
        for member in tf:
            parts = member.name.split("/")
            if root_name is None and parts and parts[0]:
                root_name = parts[0]
            component = parts[1] if len(parts) >= 2 else None
            if component in WANTED_COMPONENTS:
                seen_components.add(component)
                target = merged_target_for_member(member.name, prefix)
                if target is not None:
                    resolved_prefix = prefix.resolve()
                    resolved_target = target.resolve()
                    if resolved_target != resolved_prefix and not str(resolved_target).startswith(str(resolved_prefix) + os.sep):
                        raise RuntimeError(f"unsafe merge target: {target}")
                    extract_regular_or_dir_to_target(tf, member, target, prefix)
                    extracted_targets += 1

    missing = WANTED_COMPONENTS - seen_components
    if missing:
        raise RuntimeError(f"archive missing components: {sorted(missing)}")
    if root_name is None:
        raise RuntimeError("archive root directory was not detected")

    if extracted_targets == 0:
        raise RuntimeError("no cargo/rustc/rust-std bin/lib payloads were extracted")


def ensure_bashrc_sources_env(env_file: Path, bashrc: Path = Path("/root/.bashrc")) -> bool:
    source_line = f"source {env_file}"
    if bashrc.exists():
        existing = bashrc.read_text(encoding="utf-8")
        if source_line in existing:
            return False
    with bashrc.open("a", encoding="utf-8") as f:
        f.write(f"\n# added by bootstrap_rustc_session.py\n{source_line}\n")
    return True


def write_env_file(env_file: Path, prefix: Path, cargo_home: Path) -> None:
    env_file.write_text(
        textwrap.dedent(
            f"""\
            export PATH={prefix / 'bin'}:$PATH
            export CARGO_HOME={cargo_home}
            export RUSTUP_TOOLCHAIN=
            """
        ),
        encoding="utf-8",
    )


def write_cargo_config(cargo_home: Path, registry_url: str) -> Path:
    config = cargo_home / "config.toml"
    config.write_text(
        textwrap.dedent(
            f"""\
            [source.crates-io]
            replace-with = "openai-cargo-public"

            [source.openai-cargo-public]
            registry = "{registry_url}"
            """
        ),
        encoding="utf-8",
    )
    return config


def quote_sh(path: Path) -> str:
    return "'" + str(path).replace("'", "'\\''") + "'"


def launcher_body(tool: str, prefix: Path, cargo_home: Path) -> str:
    binary = prefix / "bin" / tool
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env sh
        {LAUNCHER_MARKER}
        set -eu
        export PATH={quote_sh(prefix / 'bin')}:$PATH
        export CARGO_HOME={quote_sh(cargo_home)}
        export RUSTUP_TOOLCHAIN=
        exec {quote_sh(binary)} "$@"
        """
    )


def write_launchers(prefix: Path, cargo_home: Path, launcher_dir: Path, force: bool) -> list[Path]:
    launcher_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for tool in ["rustc", "cargo"]:
        target = launcher_dir / tool
        body = launcher_body(tool, prefix, cargo_home)
        if target.exists() and not force:
            existing = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else ""
            if LAUNCHER_MARKER not in existing:
                raise RuntimeError(
                    f"refusing to overwrite non-generated launcher: {target}; "
                    "use --force-launchers or choose --launcher-dir"
                )
        target.write_text(body, encoding="utf-8")
        target.chmod(0o755)
        written.append(target)
    return written


def write_probe_project(probe: Path) -> None:
    (probe / "src").mkdir(parents=True, exist_ok=True)
    (probe / "Cargo.toml").write_text(
        textwrap.dedent(
            """\
            [package]
            name = "rust_install_probe_python_tarfile"
            version = "0.1.0"
            edition = "2021"

            [dependencies]
            """
        ),
        encoding="utf-8",
    )
    (probe / "src" / "main.rs").write_text(
        textwrap.dedent(
            """\
            fn main() {
                println!("rustc cargo python-tarfile probe ok: {}", add(2, 3));
            }

            fn add(a: i32, b: i32) -> i32 {
                a + b
            }
            """
        ),
        encoding="utf-8",
    )


def write_library_probe_project(probe: Path, crate_name: str, crate_version: str) -> None:
    (probe / "src").mkdir(parents=True, exist_ok=True)
    (probe / "Cargo.toml").write_text(
        textwrap.dedent(
            f"""\
            [package]
            name = "rust_library_download_probe"
            version = "0.1.0"
            edition = "2021"

            [dependencies]
            {crate_name} = "={crate_version}"
            """
        ),
        encoding="utf-8",
    )
    (probe / "src" / "main.rs").write_text(
        textwrap.dedent(
            """\
            fn main() {
                let mut buffer = itoa::Buffer::new();
                println!("library download probe ok: {}", buffer.format(12345));
            }
            """
        ),
        encoding="utf-8",
    )


def run_checked(cmd: list[str], env: dict[str, str], cwd: Path | None = None) -> tuple[str, str]:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        env=env,
        text=True,
        capture_output=True,
        timeout=300,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"command failed: {' '.join(cmd)}\nstdout={proc.stdout}\nstderr={proc.stderr}"
        )
    return proc.stdout, proc.stderr


def validate(
    prefix: Path,
    cargo_home: Path,
    probe: Path,
    library_probe: Path,
    library_crate: str,
    library_version: str,
    skip_probe: bool,
    skip_library_probe: bool,
) -> list[tuple[list[str], str, str]]:
    env = os.environ.copy()
    env["PATH"] = f"{prefix / 'bin'}:{env.get('PATH', '')}"
    env["CARGO_HOME"] = str(cargo_home)
    env["RUSTUP_TOOLCHAIN"] = ""

    commands: list[tuple[list[str], Path | None]] = [
        (["rustc", "--version"], None),
        (["rustc", "--print", "sysroot"], None),
        (["rustc", "--print", "target-libdir"], None),
        (["cargo", "--version"], None),
    ]
    if not skip_probe:
        write_probe_project(probe)
        commands.append((["cargo", "run", "--offline"], probe))
    if not skip_library_probe:
        write_library_probe_project(library_probe, library_crate, library_version)
        commands.append((["cargo", "fetch"], library_probe))
        commands.append((["cargo", "run", "--offline"], library_probe))

    outputs = []
    for cmd, cwd in commands:
        out, err = run_checked(cmd, env=env, cwd=cwd)
        outputs.append((cmd, out, err))
    return outputs


def main() -> int:
    args = parse_args()

    if args.force:
        reset_generated_paths([args.tmp, args.prefix, args.cargo_home, args.probe, args.library_probe, args.env_file])

    args.cargo_home.mkdir(parents=True, exist_ok=True)
    cargo_config: Path | None = None
    if not args.skip_registry_config:
        cargo_config = write_cargo_config(args.cargo_home, args.registry_url)

    if not have_toolchain(args.prefix):
        extract_components_with_python_tarfile(args.archive, args.tmp, args.prefix)

    write_env_file(args.env_file, args.prefix, args.cargo_home)
    patched = ensure_bashrc_sources_env(args.env_file)
    launchers: list[Path] = []
    if not args.no_install_launchers:
        launchers = write_launchers(
            args.prefix,
            args.cargo_home,
            args.launcher_dir,
            force=args.force_launchers,
        )
    outputs = validate(
        args.prefix,
        args.cargo_home,
        args.probe,
        args.library_probe,
        args.library_crate,
        args.library_version,
        args.skip_probe,
        args.skip_library_probe,
    )

    for cmd, out, err in outputs:
        print("$", " ".join(cmd))
        if out:
            print(out, end="")
        if err:
            print(err, end="", file=sys.stderr)
        print()
    print(f"env_file={args.env_file}")
    print(f"usage=source {args.env_file}")
    print(f"bashrc_patched={patched}")
    if cargo_config:
        print(f"cargo_config={cargo_config}")
        print(f"registry_url={args.registry_url}")
    if launchers:
        print("launchers=" + ",".join(str(path) for path in launchers))
        print("new_exec_usage=cargo --version && rustc --version")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())