[package]
name = "canon-rustc-v3"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "canon-rustc-v3"
path = "src/bin/canon_rustc_v3.rs"


[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
rustc-hash = "1"

[features]
default = ["rustc-driver"]
rustc-driver = []
