[build]
rustc-wrapper = "canon-rustc-v3/scripts/canon-rustc-v3"

rustflags = [
"-Dwarnings",
"-Dunused",
"-Dunused-attributes",
"-Dunused-imports",
"-Dunused-variables",
"-Ddead-code",
"-Dclippy::allow_attributes",
"-Dclippy::allow_attributes_without_reason"
]

[target.'cfg(all())']
rustflags = [
  "-Dwarnings",
  "-Ddead-code",
  "-Dclippy::allow_attributes",
  "-Dclippy::allow_attributes_without_reason"
]


[env]
CANON_RUSTC_V3_ARTIFACT_DIR = "state/rustc"
RUST_BACKTRACE = "full"
